# Generated by Django 3.1.1 on 2020-09-30 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='kogda',
            field=models.CharField(default=django.utils.timezone.now, max_length=8, verbose_name='Дата события'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='who',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Кто добавил'),
            preserve_default=False,
        ),
    ]
