# Generated by Django 3.1.1 on 2020-09-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200930_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task',
        ),
        migrations.AlterField(
            model_name='task',
            name='kogda',
            field=models.CharField(max_length=50, verbose_name='Когда будет:'),
        ),
        migrations.AlterField(
            model_name='task',
            name='who',
            field=models.CharField(max_length=50, verbose_name='Кто приглашает'),
        ),
    ]
